from __future__ import annotations

import streamlit as st

from core.pipeline_state import ensure_session_domains


st.set_page_config(
    page_title="Mini-Grid LV Toolkit",
    layout="wide",
    initial_sidebar_state="expanded",
)

ensure_session_domains(st.session_state)

st.title("Mini-Grid LV Toolkit")
st.markdown(
    """This app provides a streamlined workflow for low-voltage (LV) mini-grid design and screening, built
    for rapid iteration and early-stage exploration. The app is organized into three main steps: topology generation,
    electrical validation, and grid reinforcement optimization. The workflow is designed to be flexible, allowing users
    to move back and forth between steps while maintaining session state as the internal source of truth.
    The app is built on a heuristic MST-based layout for fast topology generation, with an integrated power-flow validation step that supports both global line assumptions and catalog-driven per-line characteristics. The reinforcement optimization
    focuses on minimum-cost line capacity upgrades without rerouting or load shifting, providing a practical tool for early-stage mini-grid design and screening.
    """
)

c1, c2, c3 = st.columns(3)

with c1:
    st.markdown(
        """
        This app provides a **first-order topology assessment** for Low-Voltage (LV) distribution networks, starting from
        building connection points and, optionally, a road layout. The goal is not detailed engineering design, but to
        quickly explore how **settlement geometry and simple planning rules** translate into pole count, network length,
        and cost.

        The workflow has two main steps. First, **pole locations are generated and buildings are associated to poles**
        using a heuristic approach. When roads are available, candidate poles are sampled along road segments; otherwise,
        poles are placed inside the settlement based on clustering of nearby buildings. Once poles are defined, they are connected into a **single radial LV network** by computing a
        **Minimum Spanning Tree (MST)**, which minimizes total cable length while avoiding loops. A final **engineering post-processing** step is then applied through the **Max LV span between poles**
        parameter. If any LV segment is longer than this threshold, it is subdivided by inserting intermediate
        support poles, preserving one connected network while avoiding unrealistically long spans.
    """
    )


    # Optional header image
    methodology_img = PathManager.ASSETS / "distribution_methodology.png"
    if methodology_img.exists():
        st.image(
            str(methodology_img),
            width='stretch',
            caption="Process flow for LV distribution network design",
        )

    st.markdown("---")

    # ---------------------------- Uploads ----------------------------
    st.subheader("Upload connection data")

    users_file = st.file_uploader(
        "Users file (GeoPackage `.gpkg` or Excel `.xlsx`) – **required**",
        type=["gpkg", "xlsx"],
        key="dist_users_file",
    )
    if users_file:
        st.success("Users file uploaded.")

    follow_roads_mode = st.radio(
        "Pole placement strategy",
        options=("Follow roads (requires roads file)", "Free placement"),
        index=0,
    )
    roads_file: Optional[Any] = None
    if follow_roads_mode.startswith("Follow roads"):
        roads_file = st.file_uploader(
            "Roads file (GeoPackage `.gpkg`)",
            type=["gpkg"],
            key="dist_roads_file",
        )
        if roads_file:
            st.success("Roads file uploaded.")
        else:
            st.info("If you don't have a roads file, switch to **Free placement**.")

    st.markdown("---")

    # ---------------------------- Parameters -------------------------
    st.subheader("Heuristic pole placement and customer association")

    col1, col2, col3 = st.columns(3)

    with col1:
        road_pole_spacing_m = st.slider(
            "Road pole spacing (candidate sampling) [m]",
            min_value=10,
            max_value=200,
            value=int(DEFAULT_SAMPLING_DISTANCE_M),
            step=5,
            help=(
                "Used ONLY when 'Follow roads' is selected. Candidate pole locations are "
                "generated by sampling points along road segments at this spacing. "
                "Smaller values → more candidate poles (denser), potentially shorter user–pole distances."
            ),
        )

    with col2:
        max_user_connection_radius_m = st.slider(
            "Max user–pole connection radius [m]",
            min_value=10,
            max_value=200,
            value=int(DEFAULT_USER_DISTANCE_M),
            step=5,
            help=(
                "Maximum distance allowed for connecting a building to an existing pole during association. "
                "Smaller values → more unassociated buildings, which may require additional poles (or become standalone candidates)."
            ),
        )

    with col3:
        max_users_per_pole = st.slider(
            "Max users per pole [#]",
            min_value=1,
            max_value=100,
            value=int(DEFAULT_MAX_ASSOCIATIONS),
            step=1,
            help=(
                "Upper limit on how many buildings can be assigned to the same pole. "
                "Smaller values → more poles to serve the same number of users."
            ),
        )

    st.subheader("Network span control (post-processing)")

    max_pole_span_m = st.slider(
        "Max LV span between poles (engineering cap) [m]",
        min_value=road_pole_spacing_m,  # cannot be smaller than the sampling distance
        max_value=150,
        value=80,
        step=5,
        help=(
            "Applied AFTER the MST is computed. If an MST edge is longer than this value, "
            "the tool inserts intermediate support poles to subdivide the span. "
            "This keeps a single connected tree while limiting long unsupported LV segments."
        ),







    )

with c3:
    st.markdown(
        """
<div class="card">
    <div class="pill">Step 3</div>
    <h4>Grid Reinforcement</h4>
    <p>
        Keep topology and load snapshot fixed, then optimize line-capacity reinforcement on existing edges
        to reduce overloads at minimum upgrade cost.
    </p>
    <p>
        The optimization does not reroute the network, does not move loads, and does not add decentralized generation.
    </p>
    <p>
        Main outputs: reinforced lines, added capacity, estimated reinforcement cost, and post-upgrade PF checks.
    </p>
</div>
""",
        unsafe_allow_html=True,
    )

    if allow_unserved_isolated:
        min_cluster_size = st.slider(
            "Minimum cluster size for LV connection",
            min_value=1,
            max_value=10,
            value=2,
            step=1,
            help=(
                "Clusters of unserved buildings smaller than this size will not get "
                "a new pole and will remain as standalone candidates."
            ),
        )
        st.info(
            "Selective coverage mode: only clusters with at least the chosen size "
            "are connected by LV. Smaller, isolated clusters are flagged as "
            "standalone candidates (red points)."
        )
    else:
        # In full-coverage mode we still pass a value, but it has no effect.
        min_cluster_size = 1
        st.info(
            "Full coverage mode: the heuristic will try to connect all buildings "
            "by LV. In very sparse areas this may lead to long LV extensions even "
            "if they exceed your intuitive distance thresholds."
        )

    st.markdown("---")

    # ---------------------------- Actions ----------------------------
    left, right, _ = st.columns([1, 1, 1])
    with left:
        run_clicked = st.button("Run LV design", type="primary", width='stretch')
    with right:
        clear_clicked = st.button("Clear results", width='stretch')

    if clear_clicked:
        st.session_state["dist_results"] = None
        st.session_state["dist_solve_seconds"] = None
        st.success("Previous results cleared.")

    # ---------------------- Run computation -------------------------
    if run_clicked:
        if users_file is None:
            st.error("Please upload a **users file** before running the LV design.")
        elif follow_roads_mode.startswith("Follow roads") and roads_file is None:
            st.error(
                "You selected **Follow roads** but didn't upload a roads file. "
                "Either upload a `.gpkg` or switch to **Free placement**."
            )
        else:
            with st.spinner("Running LV distribution design…"):
                t0 = time.perf_counter()
                try:
                    results = run_low_voltage(
                        users_file=users_file,
                        roads_file=roads_file,
                        sampling_distance=float(road_pole_spacing_m),
                        user_distance=float(max_user_connection_radius_m),
                        max_associations=int(max_users_per_pole),
                        allow_unserved_isolated=allow_unserved_isolated,
                        min_cluster_size=int(min_cluster_size),
                        max_pole_span_m=float(max_pole_span_m),
                    )
                except Exception as exc:
                    st.error(f"LV design failed: {exc}")
                    st.stop()

                elapsed = time.perf_counter() - t0
                st.session_state["dist_results"] = results
                st.session_state["dist_solve_seconds"] = elapsed

            st.success(f"Computation completed in {elapsed:.2f} seconds.")

    # ---------------------------- Results ---------------------------
    if st.session_state.get("dist_results") is not None:
        st.divider()
        st.header("Results")

        solve_time = st.session_state.get("dist_solve_seconds")
        if solve_time is not None:
            st.caption(f"Model run time: {solve_time:.2f} s")

        _show_lv_results(st.session_state["dist_results"])
    else:
        st.info("No results yet. Configure inputs and click **Run LV design**.")

st.markdown("### What Is Included")
f1, f2, f3 = st.columns(3)
f1.info("Topology generation with MST-based LV layout and downloadable network outputs.")
f2.info("Demand aggregation from `building_metadata.csv` and `category_profiles.csv` into hourly pole loads.")
f3.info("Power-flow validation with voltage checks, line loading, map overlays, and optional per-line cable catalogs.")

st.markdown(
    """
<div class="note">
    Use the sidebar to move through the workflow. For a quick start, baseline sample inputs are available in <code>examples/</code>.
</div>
""",
    unsafe_allow_html=True,
)
